### ISSUE TITLE
housekeeping: customise every repository with byline and the reflex-frp.org website

### ISSUE THREAD

**Issue by ghuntley** [reflex-frp/reflex-frp#5]
![image](https://user-images.githubusercontent.com/127353/40297641-cdcb2874-5d23-11e8-93f0-c7ed167de3f6.png)

For each of these repositories:

* [x] https://github.com/reflex-frp/reflex-platform
* [x] https://github.com/reflex-frp/reflex-frp.org
* [x] https://github.com/reflex-frp/reflex-platform
* [x] https://github.com/reflex-frp/reflex
* [x] https://github.com/reflex-frp/reflex-dom-ace
* [x] https://github.com/reflex-frp/reflex-dom
* [x] https://github.com/reflex-frp/reflex-dom-semui
* [x] https://github.com/reflex-frp/reflex-examples
* [x] https://github.com/reflex-frp/reflex-todomvc

Configure the following:
* [x] Implement description of repository
* [x] Add the tag `reflex-frp` to the repository
* [x] Change website to https://reflex-frp.org (even tho SSL is not configured yet)

**Comment by ghuntley** [comment]
🚢

**Comment by ryantrinkle** [comment]
Awesome, thanks!
